name: "Fetch DDNet Upstream"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    branches:
      - upstream-ddnet

jobs:
  rebase-ddnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: upstream-ddnet

      - run: git remote add ddnet https://github.com/ddnet/ddnet
      - run: git fetch ddnet
      - run: git rebase ddnet/master
      - run: git push origin HEAD:upstream-ddnet
